### ISSUE TITLE
Masonry Animation Test

### ISSUE THREAD

**Issue by timholz** [desandro/masonry#1028]
Hi – I was wondering how masonry animation could be modified with easing. Here is a test:
https://codepen.io/timholz/full/qpMZya/
Thanks a lot for masonry.

**Comment by desandro** [comment]
Try setting `transition-timing-function` on items with CSS.

``` css
.grid__item {
  transition-timing-function: cubic-bezier(0.500, 0.000, 0.400, 1.300)
}
```
