### ISSUE TITLE
how i can add gutter on my work 

### ISSUE THREAD

**Issue by TasioC** [desandro/masonry#1093]
i have my grid right when i put 0% on my .masonry-gutter-sizer, but when i add gutter doesn't work and goes down. i dont know what i need to change.

Thanks for the help is a really good plugin. :) 

https://codepen.io/ta_io/pen/KEbQxo

**Comment by desandro** [comment]
If your gutter is `3%` you need to account for that gutter space in your columnWidth spacing. A grid with 4 columns and 3 gutters of 3% would be:

```
( 100% - ( 3 * 3%) ) / 4 = 22.75%
```

Your grid sizes would then be:

``` css
.x1 { width: 22.75% }
.x2 { width: 48.5%; } /* 22.75 * 2 + 3% */
.x3 { width: 74.25%; } /* 22.75 * 3 + 3% * 2 */
.x4 { width: 100%; }
```
