### ISSUE TITLE
Problem with resize

### ISSUE THREAD

**Issue by jamlfy** [desandro/masonry#310]
If you place a text box within the grid items to create. And you resize the text box. No change.

``` html
<div id="container">
  <div class="item">
     <textarea></textarea>
  </div>
  <div class="item">
     <textarea></textarea>
  </div>
  ....
</div>
```

``` css
textarea {
 height  : 50px;
}
textarea:hover, textarea:focus, textarea:active {
 height  : 100px
}
```

``` javascript
$('#container').masonry({ itemSelector: '.item', gutterWidth: 4, isResizable: true } );
```

No resize, the item.
