### ISSUE TITLE
Masonry Padding Issue 

### ISSUE THREAD

**Issue by vince11829** [desandro/masonry#392]
I am not a developer and have submitted this issue myself because the person who built this site has gone MIA.  My sincere apologies as I would've submitted a test case if I knew exactly what I was doing.  I did try but had no idea what I was doing.

He used masonry jquery to display the homepage content feeds.  The issue is that the gutter width/padding between each container disappears time to time (mostly in Firefox).  I've attached screenshots below to illustrate this better.

I've included as much information as possible, I hope that we can find a solution.  Thank you for your help.

Website URL: http://www.capitalaspower.com 

Screenshot of Issue:
![image 1](https://f.cloud.github.com/assets/5281861/1004732/5a60bf02-0aa8-11e3-80a2-5db77b0f7299.png)

Screenshot of how it should display:
![image 2](https://f.cloud.github.com/assets/5281861/1004733/5a62cb8a-0aa8-11e3-8933-a5edf1322e4b.png)

Javascript:

``` javascript
define(['jquery', 'components/masonry'], function($) {
    var masonry;

    var m = {
        run: function() {
            setTimeout(function() {
                var container = document.getElementById('masonry');

                if (container) {
                    masonry = new Masonry(container, {
                        columnWidth:317,
                        gutterWidth:24
                    });
                }
            },
            250 //250ms timeout
            );
        }
    };

    return m;
}); 
```

CSS:

``` css
#masonry {
    margin-top:27px;
}

#masonry .block {
    float:left;
    width:317px;
    margin-bottom:27px;
    background:#FFF;
}

#masonry .block h3 {
    text-transform: uppercase;
    font-size:20px;
    padding:16px 20px;
    background:#252525;
    font-family:'Roboto Condensed', 'Helvetica Neue', Arial, sans-serif;
    background:url(../images/icons/bn-archives.png) #252525 no-repeat center left;
    padding-left: 51px;
}

#masonry .block h3.blog {
    background-image:url(../images/icons/blog.png);
    padding-left: 48px;
}

#masonry .block h3.publications {
    background-image:url(../images/icons/publications.png);
    padding-left: 46px;
}


#masonry .block h3.bn-archives {
    background-image:url(../images/icons/bn-archives.png);
    padding-left: 51px;
}

#masonry .block h3.working-paper-series {
    background-image:url(../images/icons/working-paper-series.png);
    padding-left: 43px;
}

#masonry .block h3.recasp-journal {
    background-image:url(../images/icons/recasp-journal.png);
    padding-left: 51px;
}

#masonry .block h3.critical-mass-forum {
    background-image:url(../images/icons/critical-mass-forum.png);
    padding-left: 51px;
}

#masonry .block h3 a {
    color:#FFF;
}

#masonry .block .posts {
    padding:18px;
}

#masonry .block .post {
    padding-bottom:19px;
    background:url(../images/post-bottom.png) repeat-x bottom left;
    margin-bottom:18px;
}

#masonry .block .posts .post:last-child {
    margin-bottom:0;
}

h2 {
    font-size:20px;
    color: #cd2727;
    margin-bottom:4px;
    font-family:'Roboto Condensed', 'Helvetica Neue', Arial, sans-serif;
}

#masonry .block .post p {
    margin-bottom:0;
}

#masonry .block .post img {
    float:left;
    margin:8px 18px 2px 0;
    width: 64px;
    height:auto;
}

.post .posted {
    color: #404040;
    font-size:11px;
    margin-bottom:10px;
    font-family: 'Helvetica Neue', Arial, sans-serif;
}

#masonry .block .go-to {
    margin:0 18px 18px 18px;
}
```
