### ISSUE TITLE
Margin Bottom Issues

### ISSUE THREAD

**Issue by kirillminiaev** [desandro/masonry#572]
Hi Desandro! Awesome plug-in and works really well, except for a small margin-bottom issue which I can't figure out (not sure if it is a bug, or my implementation). Screenshot of issue below:

![image](https://cloud.githubusercontent.com/assets/1116782/3247294/056b6386-f183-11e3-80c4-4005b51395d0.png)

You will notice above that two of the masonry blocks overlap each other ignoring any margin-bottom setting. Furthermore, the margin bottom doesn't seem to follow my actual margin-bottom settings in the CSS. Screenshot below:

![image](https://cloud.githubusercontent.com/assets/1116782/3247430/296232d2-f184-11e3-9e2f-849ad8f37c73.png)

Here is the code for each of the blocks:

CSS

``` css
.blurbs .blurb {
    background-color: #ffffff;
    display: block;
    box-shadow: 0px 0px 10px 0px #999999;
    padding: 20px 20px;
    margin-bottom: 30px;
    -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box;
    width: 24%;
}
```

jQuery

``` css
$('.blurbs').masonry({
      itemSelector: '.blurb',
      "gutter": 10
    });
}
```

I am working with the latest version of Masonry (3.1.5) through a custom Wordpress theme for Wordpress 3.9.1. I am on Windows 8.1 Chrome 35.0.1916.114.

Any help you can provide would be awesome! Thank you.
