### ISSUE TITLE
Footer problem

### ISSUE THREAD

**Issue by Pasikonik** [desandro/masonry#699]
My footer doesn't stick to the bottom of site but only when it refresh.

1# standard situation
![good]
(http://i.imgur.com/7d2JFL2.png)
2# refresh site
![bad]
(http://i.imgur.com/gvXmpPN.png)

```css
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  color: #9d9d9d;
  padding-top: 10px;
  height: 40px;
  background-color: #222222;
}
```

```javascript
  $container = $('#masonry-container')
  $container.imagesLoaded ->
    $container.masonry
      itemSelector: '.item'
      columnWidth: 220
      isAnimated: !Modernizr.csstransitions
      isFitWidth: true
```
I using: [masonry-rails](https://github.com/kristianmandrup/masonry-rails)
