### ISSUE TITLE
Fitting same-size title element above fitWidth grid

### ISSUE THREAD

**Issue by cbanksbi** [desandro/masonry#829]
I currently have the `isFitWidth: true` option set so that the grid spans the entire viewport. Above the grid I wanted to have a heading title. The current challenge is keeping it left-aligned with the grid as it resizes. So to reiterate I want the heading to always align to the left-most grid. Placing the heading inside the `.grid` container will only cause it overlap with the tiles because their positioned absolute. Is there any way I can get this to work without hardcoding values for certain breakpoints?

Here's an example of my problem: https://jsfiddle.net/fnsfytg8/

**Comment by desandro** [comment]
Sure thing, you can hack it with some CSS. See demo https://jsfiddle.net/fnsfytg8/4/


``` css
.grid {
  margin: 0 auto;
  padding-top: 80px;
}

.title {
  border: 1px solid black;
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
}
```
