### ISSUE TITLE
Strange Gutter Issue

### ISSUE THREAD

**Issue by MrHunter** [desandro/masonry#844]
Been struggling with this odd issue for the past few days, basically all I want is these images to align and have a gutter of 30px. Here is what I get in my actual code:
![screen shot 2016-03-30 at 1 57 11 pm](https://cloud.githubusercontent.com/assets/5040696/14152142/8db42bbc-f67f-11e5-854f-771b7b3483d9.png)

As you can see the first gutter is 20px while the next one is 40px, I've created a reduced test case for you to see the functionality here: http://codepen.io/MrHunter/pen/PNKaMQ

Not sure if this is a bug in the code or just me overlooking something quite simple?

**Comment by desandro** [comment]
When calcuating the grid, columnWidth and gutter are added together.

```
CC G CC G CC G CC
```

Items that span multiple columns should be as wide as the number of columns plus the gutters in between.

```
with columnWidth: 50, gutter: 30

1 column = 1 * 50px + 0 * 30px = 50px
2 columns = 2 * 50px + 1 * 30px = 130px
3 columns = 3 * 50px + 2 * 30px = 210px
```

Take a look at the gutter demo, which has `columnWidth: 160, gutter: 20`.  http://codepen.io/desandro/pen/iIbgC

``` css
.grid-item { width: 160px; }
.grid-item--width2 { width: 340px; }
.grid-item--width3 { width: 520px; }
.grid-item--width4 { width: 780px; }
```

You could use `columnWidth: 90, gutter: 30` . See demo: http://codepen.io/desandro/pen/19b4c875dc37be033ec19db129bb4749/
