### ISSUE TITLE
Gutter causes layout to shift while loading. 

### ISSUE THREAD

**Issue by lvekua** [desandro/masonry#906]
http://stackoverflow.com/questions/40222853/masonry-blocks-shift-while-loaded

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by lvekua** [comment]
http://codepen.io/lvekua/pen/vXPKkv

**Comment by desandro** [comment]
This looks like a FOUC issue. The gutters are added when Masonry is initialized after images have loaded.

``` css
.col { opacity: 0; }
/* show cols when images loaded */
.show-cols .col { opacity: 1; }
```

``` js
var $section = $('.section').imagesLoaded(function(){
  $section.addClass('show-cols');
  $section.masonry({...});
});
```

See demo http://codepen.io/desandro/pen/3cd8ce8a408ef92d067b02a0886410e0/
